### ISSUE TITLE
Memory issue on Navigation stack, Sheet & FullSheet

### ISSUE THREAD

**Issue by Suri1044** [obvios/Routing#1] opened 2024-02-02 01:15 UTC
Hi Team,
I have observed that the package manager has memory issues. I have created the sample project and included the routing package manager to test the memory and its increasing the memory on all 3 navigation cases.

I am attaching the video i have created and the sample project for reference purpose. please check and fix the issue and let me know the cause.

https://github.com/obvios/Routing/assets/68360396/8c5fb7cb-22e1-405f-ac03-c574fddf0726

[RoutingProject.zip](https://github.com/obvios/Routing/files/14132747/RoutingProject.zip)

Need Help on:
Also need help on how to create multiple Routables ie, enum LoginRoute: Routable, enum AccountRoute: Routable, enum TabRoute: Routable and include this routables as view hieararchy using  
ie, RoutingView(LoginRoute.self) { route in
            MainView(router: route)
        } 
RoutingView(AccountRoute.self) { route in
            MainView(router: route)
        } 
RoutingView(TabRoute.self) { route in
            MainView(router: route)
        } 

Let me know how to connect with you to discuss the issues. Thanks in advance.

**Comment by obvios** [comment] 2024-02-04 20:24
Hi @Suri1044 ,

Regarding your question using multiple RoutingView instances, I would recommend separating them using `TabView`. For example:

```swift
TabView {
    RoutingView(LoginRoute.self) { route in
         MainView(router: route)
    }
    RoutingView(AccountRoute.self) { route in
         MainView(router: route)
    }
}
```

Each `RoutingView` can only support one `Routable`. So that is why I recommend separating the flows with a tab view.

To create a `Routable` instance, please follow our example on our `README`

**Comment by Suri1044** [comment] 2024-02-07 02:41
Hi Team,
I have a problem when i have added different RoutingView in TabView.
Use Case:
1. I have loginview where i injected Loginview in app Content view and
after login i have screens to navigate (accounts and Tabview)

RoutingView(LoginRoute.self) { route in
         MainView(router: route)
    }

2. When i land on Tabview,  I have added different routes as suggested
by you above.

ie, TabView {

    RoutingView(HomeRoute.self) { route in
         HomeView(router: route)
    }
    RoutingView(MoreRoute.self) { route in
         MoreView(router: route)
    }
}

3. I am unable to navigate (Home tab root) when i added button from
HomeView and trying to push, Nothing working.

4. Can you please let me know why its not working? Do i need to add
the RoutingView in mainApp ContentView only ? i can't add in Tabview
as viewhierachy?

Waiting for your reply, I am actively looking on this, if not working
i need to go to default way navigationstack. Appreciate your help.


Thanks,

Suresh

**Comment by Suri1044** [comment] 2024-02-07 14:21
I have attached the sample code in git.. Please look into this so that i
can use the package manager.
Appreciate your help.

**Comment by obvios** [comment] 2024-02-07 19:17
Thank you for sharing the project, I will look into it and get back to you with my findings.

**Comment by Suri1044** [comment] 2024-02-08 00:02
@obvios : Any luck with the finding. Do you have any sample which use multiple routes in app for login, account, tab and works. That will be really helpful.

**Comment by obvios** [comment] 2024-02-08 01:26
Hi @Suri1044 ,

I looked over your project and concluded that the issues you are facing are not being caused by the `Routing` library. The issue is how you are structuring your views. You cannot nest a `RoutingView` inside another routing view.

This is why i suggested using a `TabView` to separate the `RoutingView`s.

You can do the following:
```swift
// This is okay
TabView {
     RoutingView {
          ...
    }

     RoutingView {
          ...
    }
}
```

You cannot do this:
```swift
RoutingView(ExampleRoute) { router in
      // You cannot use MainView here because it has RoutingView inside it.
      MainView()
}

MainView {
     body: some View {
         // Routing View
          RoutingView { . . .}
     }
}
```

**Comment by Suri1044** [comment] 2024-02-08 01:54
Hi Obvios/Routing,
I did add in the customTabview in the code which i provided, not inside
another routing view (not nesting). Attached screenshot for reference, Also
can you make it workable of my working code?/share any multi route code
sample plz.

Can you please confirm that can it will wrok with multiple routes or not if
i use your package Manager. If yes can you share any code reference plz,
i want to understanding how its working in multiple routes, because i don't
think its working (i may be wrong)....

Question 2
2. will same view ex: Account view  can work with multiple routes  (pushing
from multiple routes) like Route1: Login -> AccountView and Route2: TabView
-> AccountView

Regards,
Suresh

**Comment by cah-suresh-kumar04** [comment] 2024-02-08 12:01
Hi @obvios :
Attaching the video with tabview as u suggested as well, Still same issue and also attaching the sample code as well.. It will be good if some sample with multiple route explained. 

Anyways can you please look into the issue. Waiting for your reply.
[TabViewLatest.zip](https://github.com/obvios/Routing/files/14208704/TabViewLatest.zip)

https://github.com/obvios/Routing/assets/156057627/b2193c3b-0ad4-4896-8763-0f4c74df0b9c

**Comment by Suri1044** [comment] 2024-02-08 12:05
Hi @obvios :
Attaching the video with tabview as u suggested as well, Still same issue and also attaching the sample code as well.. It will be good if some sample with multiple route explained. 

Anyways can you please look into the issue. Waiting for your reply.


https://github.com/obvios/Routing/assets/68360396/09c8be8c-7f39-48a8-bb6e-6cf8349905a0

[TabViewLatest.zip](https://github.com/obvios/Routing/files/14208870/TabViewLatest.zip)

**Comment by Suri1044** [comment] 2024-02-09 00:07
@obvios : What's the point if i have we can only one Navigationcontroller for whole application. Its not going to work right?
Switching between different routes also plays major role in big application right 
and we are passing router instances in every view and that's ok with one Navigation since we can push and pop but what if i want to go to another navigation controllers view how to achieve that since we don't have router instance of that navigation here... 
Overall this will be problem in understanding the package usage without multi route switching...So i request, place a sample/example so that others will follow easily... I almost spent 3 days time (My bad i am not understanding switching routes) with package in implementing and got failured now i dont have other option other than going with the default stack in the application.

**Comment by obvios** [comment] 2024-02-09 03:01
Hi @Suri1044 ,

I will include notices on the issues you encountered. I will do my best to provide an example for your use case.

This may take a couple of days, appreciate your patience with this.

**Comment by obvios** [comment] 2024-02-09 14:21
@Suri1044 ,

I have modified your project to demonstrate the appropriate way to use the Routing package. Again, the issue is that you were nesting a `RoutingView` inside another `RoutingView`. You cannot do this, SwiftUIs `NavigationStack` won't allow this.

Here is the updated project, please see the comments I added: 
[CustomTabView.zip](https://github.com/obvios/Routing/files/14222815/CustomTabView.zip)

https://github.com/obvios/Routing/assets/38594636/9aaa49b2-019a-4401-81d4-d4ff20af4428

I will now close this issue as it is not an issue related to the Routing package, rather it was related to how it was being used. I hope I've helped you understand the issues related to your implementation.

**Closed by obvios** 2024-02-09 14:21 UTC

**Comment by obvios** [comment] 2024-02-12 19:52
Hello @Suri1044 ,

I am seeing mixed results on the memory leak you described.

I am seeing my the memory go up initially to about 30mb, however that is all. As I continue to use the app it doesn't continue increasing memory usage.

Can you confirm? Please try several times and let me know if the memory usage is consistently increasing.
